### ISSUE TITLE
Fips with go 1.20?

### ISSUE THREAD

**Issue by jimmykarily** [kairos-io/kairos#1498]
"Only 1.19.x uses our FIPS certified boring-ssl version" so we need to build our fips package using `go1.19.10`

Packages:

- [ ] immucore
- [ ] kairos-agent
- [ ] kcrypt
- [ ] kcrypt-challenger

These packages will need to consume a collection like this: https://github.com/kairos-io/packages/blob/main/packages/toolchain-go/collection.yaml which will use go 1.19.10 . Let's create a `toolchain-go-fips` collection that uses the desired version of go.

We want a golang that uses this commit of boring ssh: https://boringssl.googlesource.com/boringssl/+/ae223d6138807a13006342edfeef32e813246b39

Defined [here](https://github.com/golang/go/blob/7fe60b5df764f5a16a2c40e4412b5ed60f709192/src/crypto/internal/boring/Dockerfile#L38). Let's check the checksum of go binary in alpine (and other any other fips enabled flavor) to ensure they are not modifying the binary in any way.

@afayasa does this sound good?

**Comment by Itxaka** [comment]
packages were set to use that version aaaand we already hit an issue:

https://github.com/kairos-io/packages/pull/281


Seems that the collector is using a 1.20 exclusive feature to compare interfaces??

```
 # github.com/kairos-io/kairos/v2/pkg/config/collector
       ../../../../pkg/mod/github.com/kairos-io/kairos/v2@v2.0.3/pkg/config/collector/collector.go:150:20: interface{} does not implement comparable
       note: module requires Go 1.20
```

So we either downgrade the collector to use go 1.19 and rework whatever is doing that interface comparision or we are screwed. Not sure if this can be fixed on the consumer side?


fips/immucore is ok, as that doesn't use the collector.
fips/kcrypt is ok, no idea why? Maybe it doesnt compare?

fips/kairos-agent wont build
fips/kcrypt-challenger wont build

**Comment by Itxaka** [comment]
ah I see, kcrypt is using a really old kairos version github.com/kairos-io/kairos v1.24.3-56.0.20230329142538-b6ae4b58c07d

**Comment by Itxaka** [comment]
@mauromorales fixed the collector thing, now it should build on 1.19!

**Comment by Itxaka** [comment]
patches to the packages to make them use the newer version and build under 1.19:

 - https://github.com/kairos-io/kairos-agent/pull/59
 - https://github.com/kairos-io/kcrypt/pull/20
 - https://github.com/kairos-io/kcrypt-challenger/pull/20

**Comment by Itxaka** [comment]
Consider this done as this refered only to the packages.
